use_amcl: false
robot_base_frame: "base_link"
global_frame: "map"
goal_topic: "/move_base_simple/goal"
base_global_planner: "navfn/NavfnROS" 
base_local_planner: "base_local_planner/TrajectoryPlannerROS"
map_type: "costmap"

TrajectoryPlannerROS:
  acc_lim_x: 2.5
  acc_lim_theta: 3.2
  max_vel_x: 0.5
  min_vel_x: 0.1
  max_vel_theta: 0.5
  min_vel_theta: -0.5
  holonomic_robot: false
  sim_time: 1.0
  footprint: [[0.3, -0.15], [0.3, 0.15], [-0.3, 0.15], [-0.3, -0.15]]
  robot_radius: 0.5
  planner_frequency: 10.0
  max_global_plan_lookahead_dist: 10
  xy_goal_tolerance: 1
  yaw_goal_tolerance: 6.28

local_costmap:
  global_frame: "odom"
  robot_base_frame: "base_link"
  update_frequency: 5.0
  publish_frequency: 10.0
  static_map: true
  make_plan_clear_costmap: false

  width: 10
  height: 10
  
  resolution: 0.05
  rolling_window: true

  inflation_radius: 0.1

global_costmap:
  map_topic: "map"
  global_frame: "map"
  robot_base_frame: "base_link"
  update_frequency: 5.0
  publish_frequency: 10.0
  static_map: true
  inflation_radius: 0.5

recovery_behaviors:
  - name: conservative_reset
    type: clear_costmap_recovery/ClearCostmapRecovery
  - name: aggressive_reset
    type: clear_costmap_recovery/ClearCostmapRecovery
